version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python -m unittest discover tests  # Assuming you have unit tests for your transformations
  post_build:
    commands:
      - echo Build and test completed!
